var sitesContent = "<h1><a href='index.html'>Home</a></h1>"
sitesContent = sitesContent + "<li>"
sitesContent = sitesContent + "<h1><a href='index.html#datasci'><u>Data Science</u></a></h1>"
sitesContent = sitesContent + "<ul>"
sitesContent = sitesContent + "<li><h3><a href='visualize-bus-bunching.html'>Visualization of Bus Bunching</a></h3></li>"
sitesContent = sitesContent + "<li><h3><a href='pair-distances.html'>Pair Distances</a></h3></li>"
sitesContent = sitesContent + "<li><h3><a href='scatter-plot-time-series-grps.html'>Scatter Plot for Time Series Data in Groups</a></h3></li>"
sitesContent = sitesContent + "<li><h3><a href='summary-of-data2.html'>Summary of Data (Part 2)</a></h3></li>"
sitesContent = sitesContent + "<li><h3><a href='keywords.html'>String Patterns with Keywords</a></h3></li>"
sitesContent = sitesContent + "<li><h3><a href='one2one-features.html'>Features with One to One Correspondence</a></h3></li>"
sitesContent = sitesContent + "<li><h3><a href='missing-data.html'>Dealing with Missing Data</a></h3></li>"
sitesContent = sitesContent + "<li><h3><a href='summary-of-data.html'>Summary of Data</a></h3></li>"
sitesContent = sitesContent + "</ul>"
sitesContent = sitesContent + "</li>"
sitesContent = sitesContent + "<li>"
sitesContent = sitesContent + "<h1><a href='index.html#simulate'><u>Simulation</u></a></h1>"
sitesContent = sitesContent + "<ul>"
sitesContent = sitesContent + "<li><h3><a href='ising.html'>Ising Model</a></h3></li>"
sitesContent = sitesContent + "</ul>"
sitesContent = sitesContent + "</li>"
sitesContent = sitesContent + "<li>"
sitesContent = sitesContent + "<h1><a href='index.html#code'><u>Coding</u></a></h1>"
sitesContent = sitesContent + "<ul>"
sitesContent = sitesContent + "<li><h3><a href='ligand.html'>Ligands On a Cluster</a></h3></li>"
sitesContent = sitesContent + "</ul>"
sitesContent = sitesContent + "</li>"
sitesContent = sitesContent + "<li>"
sitesContent = sitesContent + "<h1><a href='index.html#interest'><u>Interest</u></a></h1>"
sitesContent = sitesContent + "<ul>"
sitesContent = sitesContent + "<li><h3><a href='features-xiangqi.html'>Features of Xiangqi Pieces</a></h3></li>"
sitesContent = sitesContent + "<li><h3><a href='about-xiangqi.html'>About Xiangqi Pieces</a></h3></li>"
sitesContent = sitesContent + "</ul>"
sitesContent = sitesContent + "</li>"
sitesContent = sitesContent + "</ul>"

document.getElementById("template-content").innerHTML = sitesContent
